django-story-book-master/django-story-book-master/story book/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story.urls')),

]

django-story-book-master/django-story-book-master/story book/story/urls.py
from django.urls import path
from . import views
app_name='story'

urlpatterns = [
    path('', views.story_list,name='story_list'),
    path('<slug:category_slug>',views.story_list,name="story_category"),
    path('<int:id>/',views.story_detail,name='story_detail'),
    path('search/',views.search_story,name="story_search"),
    path('tag/<slug:tag_slug>',views.story_list,name="story_by_tag")
  
   
    

]

django-story-book-master/django-story-book-master/story book/story/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=150,db_index=True,)
    slug=models.SlugField(unique=True)
    class Meta:
        ordering=('-name',)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('story:story_category',args=[self.slug,])
class Story(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)   
    title=models.CharField(max_length=150)
    body=models.TextField()
    des=models.TextField()   
    publish=models.DateTimeField(auto_now_add=True)
    tags=TaggableManager()
    class Meta:
        ordering=('-publish',)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('story:story_detail',args=[self.id,])    

django-story-book-master/django-story-book-master/story book/story/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import PageNotAnInteger,Paginator,EmptyPage
from django.db.models import Q
import random
from taggit.models import Tag
from django.db.models import Count

# Create your views here.
from .models import Story,Category

def story_list(request,category_slug=None,tag_slug=None):
    category=None
    categories=Category.objects.all()
    story=Story.objects.all()
    paginator=Paginator(story,4)
    page=request.GET.get('page')
    tag=None
    try:
        story=paginator.page(page)
    except PageNotAnInteger:
        story=paginator.page(1) 
    except EmptyPage:
        story=paginator.page(paginator.num_pages)       
    if category_slug:
        story=Story.objects.all()
        category=get_object_or_404(Category,slug=category_slug)
        story=story.filter(category=category)
        paginator=Paginator(story,3)
        page=request.GET.get('page')
        try:
            story=paginator.page(page)
        except PageNotAnInteger:
            story=paginator.page(1) 
        except EmptyPage:
            story=paginator.page(paginator.num_pages)   
    all_story=list(Story.objects.all())
    recent_story=random.sample(all_story,3)
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        story=Story.objects.filter(tags__in=[tag])
        paginator=Paginator(story,2)
        page=request.GET.get('page')
        try:
            story=paginator.page(page)
        except PageNotAnInteger:
            story=paginator.page(1) 
        except EmptyPage:
            story=paginator.page(paginator.num_pages)   
    return render(request,'story/story_list.html',{
                                                   'categories':categories,
                                                   'story':story,
                                                   'category':category,
                                                   'page':page,
                                                   'recent_story':recent_story,
                                                   'tag':tag
                                                   })  
                                                     
def story_detail(request,id):
    story=get_object_or_404(Story,id=id)
    all_story=list(Story.objects.exclude(id=id))
    like_story=random.sample(all_story,3)

    ############# TAGS

    post_tags_ids = Story.tags.values_list('id', flat=True)
    similar_posts = Story.objects.filter(tags__in=post_tags_ids).exclude(id=story.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:3]
    
    #############
    return render(request,'story/story_detail.html',{'story':story,'like_story':like_story,})
   ############## 


def search_story(request):
    query=None
    results=[]
    if request.method =="GET"  :
        query=request.GET.get("search")  
        results=Story.objects.filter(Q(title__icontains=query) | Q(body__icontains=query))
    return render(request,'story/search.html',{'query':query,'results':results,})    



###### select random 3 object form model 
##### select recent 3 object from model
##### select 1 random onbject from the model

django-story-book-master/django-story-book-master/story book/story/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% block title %}<title>story book</title>{% endblock %}
  </head>
  <body>
   <!-- As a heading -->
    <nav class="navbar navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">Story book</span>
    </nav>
    {% block body %}

     {% endblock %}
     <footer class="cs-footer mt-4 bg-dark pt-5 pt-md-6 pt-lg-7">
      <div class="container pt-3 pt-md-0">
        <div class="pb-md-4 text-center">
          <h3 class="text-light font-weight-light mb-3">Do not read all story?</h3>
          <h2 class="text-light mb-5">Read all story for your interest</h2>
          
        </div>
      </div>
      </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

django-story-book-master/django-story-book-master/story book/story/templates/pagination.html
<div class="">
    <span class="">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}

    <span class="">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>

    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

django-story-book-master/django-story-book-master/story book/story/templates/story/search.html
{% extends 'base.html' %}

{% block title %}
<title>search story</title>
{% endblock%}


{% block body %}
<div class="container" >
    <h1>This is search page</h1>
    {% if query %}
    <h3>{% with results.count as total_results %}
        Found {{total_results}} results
        {% endwith %}
    </h3>
     {% for x in results %}
     <div class="mt-3">
        <a href="{{x.get_absolute_url}}">
            <h2>{{x.title}}</h2>
        </a>
        <p>{{x.des}}</p>
    </div>
    {% empty %}
    <h3>There is no query</h3>
    {% endfor %}
    {% else %}
    <h3>Please search for a right query ,you don't write any query</h3>
    {% endif %}


</div>
{% endblock %}

django-story-book-master/django-story-book-master/story book/story/templates/story/story_detail.html
{% extends 'base.html' %}

{% block title %}
<title>{{story.title}}</title>
{% endblock%}


{% block body %}
    <div class='container'>
    <h2 class="text-center">{{story.title}}</h2><hr>
    <p class="lead">{{story.body|safe}}</p>
    </div>
    <hr>
    <div class="container">
    <h2>YOU MAY ALSO LIKE:</h2>
    {% for x in like_story %}
    <a href="{{x.get_absolute_url}}"><h5>{{x.title}}</h5></a>
    {% endfor%}
    <br>


    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar story yet.
    {% endfor %}</div>


{% endblock %}

django-story-book-master/django-story-book-master/story book/story/templates/story/story_list.html
{% extends 'base.html' %}

{% block title %}
<title>story book</title>
{% endblock%}


{% block body %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Story Book</h1>
    <p class="lead">you can find here some short stories</p>
</div>
<div class="container">
    <div class="jumbotron mt-3">
        <h3>Categories</h3>
        <ul>
            <li>
                <a href="{% url 'story:story_list' %}">All</a>
            </li>
            {% for x in categories %}
            <li>
                <a href="{{x.get_absolute_url}}">{{x.name}}</a>
            </li>

            {% endfor %}
            </li>
        </ul>
    </div>
    <div>
        <hr>



       
         <form action="{% url 'story:story_search' %}" class="form-inline" method="get">
             <div class="form-group mb-2">
                <h3> {% if category %}{{category.name}}{% else %}All-STORY{% endif  %}</h3>
             </div>
             <div class="form-group mx-sm-3 mb-2">
                 <label class="sr-only">Search</label>
                 <input name="search" class="form-control" >

             </div>
            <button type="submit" class="btn btn-success btn-lg">Search</button>
         </form>

        <hr>

        {% for x in story %}
        <div class="mt-3">
            <a href="{{x.get_absolute_url}}">
                <h2>{{x.title}}</h2>
            </a>

            Tag: {% for tag in x.tags.all %}
            <a href='{% url "story:story_by_tag" tag.slug %}'>{{tag.name}}</a>
            {% if not forloop.last %},{% endif %}
            {% endfor %}

            
            <p>{{x.des}}</p>


        </div>
        {% endfor %}



        <hr>
        <h3 class="text-center">{% include 'pagination.html' with page=story %}</h3>
         <hr>
         <h3>Recent three story:</h3> 
         {% for x in recent_story %}
         <a href="{{recent_story.get_absolute_url}}">
            <h6>{{x.title}}</h6>
        </a>
         {% endfor %}
      

    </div>
</div>

{% endblock %}